# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\a_spending_by_category.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(868, 652)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topbox = QtWidgets.QWidget(parent=Form)
        self.topbox.setMaximumSize(QtCore.QSize(16777215, 40))
        self.topbox.setObjectName("topbox")
        self.label = QtWidgets.QLabel(parent=self.topbox)
        self.label.setGeometry(QtCore.QRect(10, 10, 798, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.topbox)
        self.widget = QtWidgets.QWidget(parent=Form)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.categoriesWidget = QtWidgets.QWidget(parent=self.widget)
        self.categoriesWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.categoriesWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.categoriesWidget.setObjectName("categoriesWidget")
        self.horizontalLayout.addWidget(self.categoriesWidget)
        self.chartWidget = QtWidgets.QWidget(parent=self.widget)
        self.chartWidget.setObjectName("chartWidget")
        self.horizontalLayout.addWidget(self.chartWidget)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FullAccount"))
        self.label.setText(_translate("Form", "Spending by Category"))
