# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\category_edit.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(554, 616)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.categoryName = QtWidgets.QLineEdit(parent=Form)
        self.categoryName.setObjectName("categoryName")
        self.verticalLayout.addWidget(self.categoryName)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.keywordinput = QtWidgets.QLineEdit(parent=Form)
        self.keywordinput.setObjectName("keywordinput")
        self.horizontalLayout_2.addWidget(self.keywordinput)
        self.addKeyword = QtWidgets.QPushButton(parent=Form)
        self.addKeyword.setObjectName("addKeyword")
        self.horizontalLayout_2.addWidget(self.addKeyword)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.categoryKeywords = QtWidgets.QListWidget(parent=Form)
        self.categoryKeywords.setObjectName("categoryKeywords")
        self.verticalLayout.addWidget(self.categoryKeywords)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.deleteCategoryBtn = QtWidgets.QPushButton(parent=Form)
        self.deleteCategoryBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.deleteCategoryBtn.setObjectName("deleteCategoryBtn")
        self.horizontalLayout.addWidget(self.deleteCategoryBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.saveCategoryChangesBtn = QtWidgets.QPushButton(parent=Form)
        self.saveCategoryChangesBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.saveCategoryChangesBtn.setObjectName("saveCategoryChangesBtn")
        self.horizontalLayout.addWidget(self.saveCategoryChangesBtn)
        self.cancelCategoryChangesBtn = QtWidgets.QPushButton(parent=Form)
        self.cancelCategoryChangesBtn.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cancelCategoryChangesBtn.setObjectName("cancelCategoryChangesBtn")
        self.horizontalLayout.addWidget(self.cancelCategoryChangesBtn)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FullAccount"))
        self.label.setText(_translate("Form", "Modify Category"))
        self.addKeyword.setText(_translate("Form", "Add Keyword"))
        self.deleteCategoryBtn.setText(_translate("Form", "Delete Category"))
        self.saveCategoryChangesBtn.setText(_translate("Form", "Save"))
        self.cancelCategoryChangesBtn.setText(_translate("Form", "Cancel"))
