# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\importbuilder.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


