# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\importtransactions.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 226)
        self.label_9 = QtWidgets.QLabel(parent=Form)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 161, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.loadCSVFileBtn = QtWidgets.QPushButton(parent=Form)
        self.loadCSVFileBtn.setGeometry(QtCore.QRect(10, 70, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.loadCSVFileBtn.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/pyros/.designer/backup/icons/csv.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.loadCSVFileBtn.setIcon(icon)
        self.loadCSVFileBtn.setObjectName("loadCSVFileBtn")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.importdetailslabel = QtWidgets.QLabel(parent=Form)
        self.importdetailslabel.setEnabled(True)
        self.importdetailslabel.setGeometry(QtCore.QRect(10, 110, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.importdetailslabel.setFont(font)
        self.importdetailslabel.setText("")
        self.importdetailslabel.setWordWrap(True)
        self.importdetailslabel.setObjectName("importdetailslabel")
        self.closeBtn = QtWidgets.QPushButton(parent=Form)
        self.closeBtn.setEnabled(True)
        self.closeBtn.setGeometry(QtCore.QRect(320, 200, 75, 23))
        self.closeBtn.setObjectName("closeBtn")
        self.importBtn = QtWidgets.QPushButton(parent=Form)
        self.importBtn.setEnabled(False)
        self.importBtn.setGeometry(QtCore.QRect(260, 70, 131, 23))
        self.importBtn.setObjectName("importBtn")
        self.label_10 = QtWidgets.QLabel(parent=Form)
        self.label_10.setGeometry(QtCore.QRect(10, 200, 271, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FullAccount"))
        self.label_9.setText(_translate("Form", "Select a csv file to begin."))
        self.loadCSVFileBtn.setText(_translate("Form", "CSV File"))
        self.label.setText(_translate("Form", "Import a Transactions File (CSV)"))
        self.closeBtn.setText(_translate("Form", "Close"))
        self.importBtn.setText(_translate("Form", "Import Transactions"))
        self.label_10.setText(_translate("Form", "Dont forget to refresh your transactions list"))
