# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\main.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(878, 758)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menuBar = QtWidgets.QWidget(parent=self.centralwidget)
        self.menuBar.setMinimumSize(QtCore.QSize(115, 0))
        self.menuBar.setMaximumSize(QtCore.QSize(115, 16777215))
        self.menuBar.setObjectName("menuBar")
        self.settingsBtn = QtWidgets.QPushButton(parent=self.menuBar)
        self.settingsBtn.setGeometry(QtCore.QRect(10, 50, 101, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("h:\\development\\python\\fullaccount\\venv\\icons/settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settingsBtn.setIcon(icon)
        self.settingsBtn.setObjectName("settingsBtn")
        self.homeBtn = QtWidgets.QPushButton(parent=self.menuBar)
        self.homeBtn.setGeometry(QtCore.QRect(10, 10, 101, 30))
        self.homeBtn.setToolTip("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("h:\\development\\python\\fullaccount\\venv\\icons/home.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.homeBtn.setIcon(icon1)
        self.homeBtn.setIconSize(QtCore.QSize(24, 16))
        self.homeBtn.setObjectName("homeBtn")
        self.horizontalLayout_2.addWidget(self.menuBar)
        self.contentBox = QtWidgets.QWidget(parent=self.centralwidget)
        self.contentBox.setObjectName("contentBox")
        self.horizontalLayout_2.addWidget(self.contentBox)
        self.contentBox.raise_()
        self.menuBar.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "FullAccount"))
        self.settingsBtn.setText(_translate("MainWindow", "Settings"))
        self.homeBtn.setText(_translate("MainWindow", "Home"))
