# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\setdateformat_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(425, 430)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 311, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.dateselect = QtWidgets.QComboBox(parent=Form)
        self.dateselect.setGeometry(QtCore.QRect(10, 100, 241, 22))
        self.dateselect.setObjectName("dateselect")
        self.label_2 = QtWidgets.QLabel(parent=Form)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName("label_2")
        self.saveBtn = QtWidgets.QPushButton(parent=Form)
        self.saveBtn.setGeometry(QtCore.QRect(250, 400, 75, 23))
        self.saveBtn.setObjectName("saveBtn")
        self.cancelBtn = QtWidgets.QPushButton(parent=Form)
        self.cancelBtn.setGeometry(QtCore.QRect(330, 400, 75, 23))
        self.cancelBtn.setObjectName("cancelBtn")
        self.opencsvfileBtn = QtWidgets.QPushButton(parent=Form)
        self.opencsvfileBtn.setGeometry(QtCore.QRect(10, 170, 101, 23))
        self.opencsvfileBtn.setObjectName("opencsvfileBtn")
        self.label_3 = QtWidgets.QLabel(parent=Form)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 331, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.tableWidget = QtWidgets.QTableWidget(parent=Form)
        self.tableWidget.setGeometry(QtCore.QRect(10, 200, 401, 192))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FullAccount"))
        self.label.setText(_translate("Form", "Set Date Format"))
        self.label_2.setText(_translate("Form", "Select the date format your csv data uses. If the date format is incorrect when the transactions are imported, it will result in incorrect dates being set for each transaction."))
        self.saveBtn.setText(_translate("Form", "Save"))
        self.cancelBtn.setText(_translate("Form", "Cancel"))
        self.opencsvfileBtn.setText(_translate("Form", "Open CSV File"))
        self.label_3.setText(_translate("Form", "Need to look at your csv file provided by your bank to see the date format?"))
