# Form implementation generated from reading ui file 'h:\development\python\fullaccount\venv\transactions.ui'
#
# Created by: PyQt6 UI code generator 6.8.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(811, 784)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addSingleTransactionBtn = QtWidgets.QPushButton(parent=Form)
        self.addSingleTransactionBtn.setMinimumSize(QtCore.QSize(150, 0))
        self.addSingleTransactionBtn.setMaximumSize(QtCore.QSize(150, 16777215))
        self.addSingleTransactionBtn.setObjectName("addSingleTransactionBtn")
        self.horizontalLayout.addWidget(self.addSingleTransactionBtn)
        self.importTransactionCSVBtn = QtWidgets.QPushButton(parent=Form)
        self.importTransactionCSVBtn.setMinimumSize(QtCore.QSize(200, 0))
        self.importTransactionCSVBtn.setMaximumSize(QtCore.QSize(200, 16777215))
        self.importTransactionCSVBtn.setObjectName("importTransactionCSVBtn")
        self.horizontalLayout.addWidget(self.importTransactionCSVBtn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.transactionsTable = QtWidgets.QTableWidget(parent=Form)
        self.transactionsTable.setAlternatingRowColors(True)
        self.transactionsTable.setObjectName("transactionsTable")
        self.transactionsTable.setColumnCount(0)
        self.transactionsTable.setRowCount(0)
        self.verticalLayout.addWidget(self.transactionsTable)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "FullAccount"))
        self.addSingleTransactionBtn.setText(_translate("Form", "Add Single Transaction"))
        self.importTransactionCSVBtn.setText(_translate("Form", "Import a Transaction File (CSV)"))
        self.transactionsTable.setSortingEnabled(True)
